name: Run Gradle on Push
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@62cce3c597efd445cd71ee868887b8b1117703a7 # v2.9.0

      - name: Execute Gradle build
        run: ./gradlew test integrationTest --tests com.salesforce.revoman.integration.pokemon.PokemonTest
